os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

 before_install:
  - git submodule update --init --recursive

script:
 - "echo \"Build ${TRAVIS_BRANCH}:$(git rev-parse --short HEAD) Started\""
 - docker build --build-arg BUILD_NUMBER=$(git rev-parse --short HEAD) --build-arg VERSION=${TRAVIS_BRANCH} --build-arg RELEASE=$(git rev-parse --short HEAD) -t sf-exporter-runtime .
after_success:
 - echo "Build $(git rev-parse --short HEAD) Passed!"
after_failure:
 - echo "Build $(git rev-parse --short HEAD) Failed!"

after_script:
 - docker rmi sf-exporter-runtime
 - docker image prune -f

branches:
  only:
  - /.*/
